version: 2
jobs:
  build-ami:
    docker:
      - image: hashicorp/packer:1.3.4
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Validate centos image
          command: packer validate centos-ami-template.json
      - run:
          name: Build CentOS AMI
          command: |
            packer build \
              -var "aws_region=${AWS_REGION}" \
              -var "aws_access_key=${AWS_ACCESS_KEY}" \
              -var "aws_secret_key=${AWS_SECRET_KEY}" \
              centos-ami-template.json
workflows:
  version: 2
  validate-and-build:
    jobs:
      - build-ami:
          filters:
            # TODO: change branch
            branches:
              only:
                - assignment6
                - assignment5
                - master
